// @flow
const assert = require('assert');

const cards = [
  'Abrade',
  'Abrupt Decay',
  'Academy Rector',
  'Accumulated Knowledge',
  'Acidic Slime',
  'Ancestral Recall',
  'Ancestral Vision',
  'Ancient Grudge',
  'Ancient Tomb',
  'Animate Dead',
  'Arbor Elf',
  'Arcane Savant',
  'Arid Mesa',
  'Armageddon',
  'Ashen Rider',
  'Ashiok, Nightmare Weaver',
  'Azorius Signet',
  'Badlands',
  'Baleful Strix',
  'Basalt Monolith',
  'Bazaar of Baghdad',
  'Beast Within',
  'Birds of Paradise',
  'Black Lotus',
  'Blackcleave Cliffs',
  'Blast from the Past',
  'Blightsteel Colossus',
  'Blood Crypt',
  'Bloodstained Mire',
  'Bojuka Bog',
  'Booster Tutor',
  'Botanical Sanctum',
  'Brainstorm',
  'Breeding Pool',
  'Bribery',
  'Buried Alive',
  'Cabal Therapy',
  'Celestial Colonnade',
  'Censor',
  'Chandra, Torch of Defiance',
  'Channel',
  'Chart a Course',
  'Chrome Mox',
  'Coalition Relic',
  'Coercive Portal',
  'Coldsteel Heart',
  'Commit // Memory',
  'Compulsive Research',
  'Consecrated Sphinx',
  'Control Magic',
  'Counterspell',
  'Courser of Kruphix',
  'Craterhoof Behemoth',
  'Creeping Tar Pit',
  'Cryptic Command',
  'Dack Fayden',
  'Damnation',
  'Daretti, Scrap Savant',
  'Dark Confidant',
  'Dark Ritual',
  'Darkslick Shores',
  'Daze',
  'Deceiver Exarch',
  'Deep Analysis',
  'Delay',
  'Demonic Tutor',
  'Deranged Hermit',
  'Diabolic Edict',
  'Dig Through Time',
  'Dimir Signet',
  'Dire Fleet Daredevil',
  'Disallow',
  'Dismember',
  'Dispel',
  'Double Stroke',
  'Dryad Arbor',
  'Duress',
  'Edric, Spymaster of Trest',
  'Electrolyze',
  'Elves of Deep Shadow',
  'Elvish Mystic',
  'Emrakul, the Aeons Torn',
  'Emrakul, the Promised End',
  'Enlightened Tutor',
  'Ensnaring Bridge',
  'Entomb',
  'Essence Scatter',
  'Eternal Witness',
  'Exhume',
  'Fact or Fiction',
  'Faith\'s Fetters',
  'Faithless Looting',
  'Fastbond',
  'Fatal Push',
  'Fiery Confluence',
  'Fire // Ice',
  'Firebolt',
  'Flooded Strand',
  'Flusterstorm',
  'Forbid',
  'Force of Will',
  'Force Spike',
  'Frantic Search',
  'Fyndhorn Elves',
  'Gaea\'s Cradle',
  'Garruk, Wildspeaker',
  'Gifts Ungiven',
  'Gilded Lotus',
  'Gitaxian Probe',
  'Glen Elendra Archmage',
  'Goblin Welder',
  'Godless Shrine',
  'Golgari Signet',
  'Grave Titan',
  'Green Sun\'s Zenith',
  'Grim Monolith',
  'Griselbrand',
  'Gush',
  'Hallowed Fountain',
  'Harmonize',
  'Hostage Taker',
  'Imperial Recruiter',
  'Inferno Titan',
  'Inquisition of Kozilek',
  'Intuition',
  'Inventor\'s Fair',
  'Izzet Charm',
  'Izzet Signet',
  'Jace Beleren',
  'Jace, the Mind Sculptor',
  'Jace, Vryn\'s Prodigy',
  'Joraga Treespeaker',
  'Kambal, Consul of Allocation',
  'Karakas',
  'Karn Liberated',
  'Karn, Scion of Urza',
  'Kiki-Jiki, Mirror Breaker',
  'Kitesail Freebooter',
  'Kolaghan\'s Command',
  'Lavaclaw Reaches',
  'Leovold, Emissary of Trest',
  'Library of Alexandria',
  'Life from the Loam',
  'Lightning Bolt',
  'Liliana of the Veil',
  'Liliana, Death\'s Majesty',
  'Lingering Souls',
  'Living Death',
  'Llanowar Elves',
  'Lodestone Golem',
  'Looter il-Kor',
  'Lotus Bloom',
  'Lotus Cobra',
  'Makeshift Mannequin',
  'Mana Confluence',
  'Mana Crypt',
  'Mana Drain',
  'Mana Leak',
  'Mana Tithe',
  'Mana Vault',
  'Marsh Flats',
  'Memory Jar',
  'Mental Misstep',
  'Metalworker',
  'Mind Twist',
  'Mindslaver',
  'Miscalculation',
  'Misdirection',
  'Mishra\'s Factory',
  'Mishra\'s Workshop',
  'Misty Rainforest',
  'Monastery Mentor',
  'Mox Diamond',
  'Mox Emerald',
  'Mox Sapphire',
  'Mox Jet',
  'Mox Opal',
  'Mox Pearl',
  'Mox Ruby',
  'Muddle the Mixture',
  'Mulldrifter',
  'Murderous Cut',
  'Mutavault',
  'Myr Battlesphere',
  'Mystic Confluence',
  'Mystical Tutor',
  'Natural Order',
  'Nature\'s Claim',
  'Necromancy',
  'Necropotence',
  'Negate',
  'Noble Hierarch',
  'Notion Thief',
  'Oath of Druids',
  'Opposition',
  'Oracle of Mul Daya',
  'Overgrown Tomb',
  'Pack Rat',
  'Painful Truths',
  'Path to Exile',
  'Pentad Prism',
  'Pestermite',
  'Phantasmal Image',
  'Phyrexian Metamorph',
  'Phyrexian Revoker',
  'Plateau',
  'Polluted Delta',
  'Ponder',
  'Portent',
  'Preordain',
  'Primal Command',
  'Primeval Titan',
  'Pyroblast',
  'Rakdos Signet',
  'Reanimate',
  'Reclamation Sage',
  'Recurring Nightmare',
  'Red Elemental Blast',
  'Regrowth',
  'Remand',
  'Repeal',
  'Restoration Angel',
  'Riftwing Cloudskate',
  'Rishadan Port',
  'Rofellos, Llanowar Emissary',
  'Sakura-Tribe Elder',
  'Scalding Tarn',
  'Scrubland',
  'Seachrome Coast',
  'Search for Tomorrow',
  'Sensei\'s Divining Top',
  'Sentinel Dispatch',
  'Shallow Grave',
  'Shelldock Isle',
  'Show and Tell',
  'Simic Signet',
  'Skullclamp',
  'Snapcaster Mage',
  'Sneak Attack',
  'Sol Ring',
  'Solumn Simulacrum',
  'Sorcerous Spyglass',
  'Soulfire Grand Master',
  'Sower of Temptation',
  'Spell Pierce',
  'Spell Queller',
  'Spell Snare',
  'Spellseeker',
  'Sphere of Resistence',
  'Spike, Tournament Grinder',
  'Spirebuff Canal',
  'Splinter Twin',
  'Steam Vents',
  'Steel Sabotage',
  'Stifle',
  'Strip Mine',
  'Sundering Titan',
  'Supreme Will',
  'Swan Song',
  'Swords to Plowshares',
  'Sylvan Caryatid',
  'Sylvan Library',
  'Taiga',
  'Telling Time',
  'Terastodon',
  'Tezzeret the Seeker',
  'Tezzeret, Agent of Bolas',
  'The Tabernacle at Pendrell Vale',
  'Thing in the Ice',
  'Thirst for Knowledge',
  'Thorn of Amethyst',
  'Thoughtseize',
  'Thran Dynamo',
  'Through the Breach',
  'Time Vault',
  'Time Walk',
  'Tinker',
  'Tolarian Academy',
  'Tooth and Nail',
  'Torrential Gearhulk',
  'Toxic Deluge',
  'Treachery',
  'Treasure Cruise',
  'Trinisphere',
  'Trinket Mage',
  'Tropical Island',
  'True-Name Nemesis',
  'Trygon Predator',
  'Tundra',
  'Ugin, the Spirit Dragon',
  'Unburial Rites',
  'Underground Sea',
  'Upheaval',
  'Urborg, Tomb of Yawgmoth',
  'Utopia Sprawl',
  'Vampiric Tutor',
  'Vendilion Clique',
  'Venser, Shaper Savant',
  'Volcanic Island',
  'Voltaic Key',
  'Warping Wail',
  'Wasteland',
  'Watery Grave',
  'Westvale Abbey',
  'Wheel of Fortune',
  'Who // What // Where // When // Why',
  'Wildfire',
  'Windswept Heath',
  'Winter Orb',
  'Wooded Foothills',
  'Woodfall Primus',
  'World Breaker',
  'Worldspine Wurm',
  'Worn Powerstone',
  'Wurmcoil Engine',
  'Yawgmoth\'s Will',
  'Young Pyromancer',
  'Zealous Conscripts',
]

for (let i = 0; i < cards.length; i++) {
  const card = cards[i];
  if (cards.indexOf(card) !== i) {
    throw new Error(`Duplicate card: ${card}`);
  }
}

module.exports = cards;











